#ifndef MSG_TYPE_H
#define MSG_TYPE_H

#define MSG_TYPE_PING 0

#define MSG_TYPE_NOSTR_GET_PUBLIC_KEY 1
#define MSG_TYPE_NOSTR_SIGN_EVENT 2
#define MSG_TYPE_NOSTR_GET_RELAYS 3
#define MSG_TYPE_NOSTR_NIP04_ENCRYPT 4
#define MSG_TYPE_NOSTR_NIP04_DECRYPT 5
#define MSG_TYPE_NOSTR_NIP44_ENCRYPT 6
#define MSG_TYPE_NOSTR_NIP44_DECRYPT 7

#define MSG_TYPE_ECHO 11
#define MSG_TYPE_UPDATE_KEY 12
#define MSG_TYPE_REMOVE_KEY 13
#define MSG_TYPE_GET_TEMP_PUBKEY 14

#endif