#ifndef MSG_TYPE_H
#define MSG_TYPE_H

#define MES_TYPE_PING = 0;

#define MES_TYPE_NOSTR_GET_PUBLIC_KEY 1
#define MES_TYPE_NOSTR_SIGN_EVENT 2
#define MES_TYPE_NOSTR_GET_RELAYS 3
#define MES_TYPE_NOSTR_NIP04_ENCRYPT 4
#define MES_TYPE_NOSTR_NIP04_DECRYPT 5
#define MES_TYPE_NOSTR_NIP44_ENCRYPT 6
#define MES_TYPE_NOSTR_NIP44_DECRYPT 7

#define MES_TYPE_ECHO = 11;
#define MES_TYPE_UPDATE_KEY = 12;
#define MES_TYPE_REMOVE_KEY = 13;

#endif