
#define MES_TYPE_NOSTR_GET_PUBLIC_KEY 1
#define MES_TYPE_NOSTR_SIGN_EVENT 2
#define MES_TYPE_NOSTR_GET_RELAYS 3
#define MES_TYPE_NOSTR_NIP04_ENCRYPT 4
#define MES_TYPE_NOSTR_NIP04_DECRYPT 5
#define MES_TYPE_NOSTR_NIP44_ENCRYPT 6
#define MES_TYPE_NOSTR_NIP44_DECRYPT 7